---
title: "Task  5"
author: "Terézia Balážová"
date: "1.12.2025"
format:
  html:
    embed-resources: true
editor: source
---

# London

# Task 3
### import real data

```{r}
library(dplyr)
library(readxl)
```

```{r}
LONDON_real_data <- read.csv("london-borough-profiles-2016 Data set.csv")
```

### inspect real data London


### The Interrogation
```{r}
# 1.Select all areas that are located in Inner London.
inner_London <- LONDON_real_data |>
  select(Area.name,Inner..Outer.London, Employment.rate......2015.)|>
  mutate(log_inner_london =Inner..Outer.London == "Inner London")

```


```{r}
# 2.what is the largest migrant population?
migrant_p_London <- LONDON_real_data |>
  select(Area.name,Largest.migrant.population.by.country.of.birth..2011. ,X..of.largest.migrant.population..2011.)|>
  
arrange(desc(X..of.largest.migrant.population..2011.))|>
  
head(10)

colnames(migrant_p_London) <- c("Area","Migrant population_A",
                               "percento_ m.p.")

str(migrant_p_London)

```

```{r}
# 3.what is the average age of highest population in area, in 2016
highest_population_age <- LONDON_real_data |>
  select(Average.Age..2016, Area.name, GLA.Population.Estimate.2016) |>
  arrange(desc(Average.Age..2016))
highest_population_age
```

```{r}
# 4.how many household are in the area,convert to numeric.
 Number_of_households <- LONDON_real_data|>
    mutate(household_n = gsub(",", ".", GLA.Population.Estimate.2016 ),
           average_household = as.numeric(household_n))|>
    select(Area.name,household_n,average_household,GLA.Population.Estimate.2016)|>
    arrange(desc(household_n))|>
    head(10)

  Number_of_households
```

```{r}
# 5. Income for households in London

Income<-LONDON_real_data|>
  select( Area.name,Gross.Annual.Pay...2015.,Gross.Annual.Pay...Male..2015.,Gross.Annual.Pay...Female..2015.,Modelled.Household.median.income.estimates.2012.13)

Income_<- Income %>%
  mutate(
    annual_Pay = gsub("£|,", "", Gross.Annual.Pay...2015.),
    Male_income = gsub("£|,", "",Gross.Annual.Pay...Male..2015.),
    Female_income = gsub("£|,", "",Gross.Annual.Pay...Female..2015.)
     )|>
  
  mutate(Annual_Pay_n = as.character(as.numeric(annual_Pay)),
         Male_Income_n = as.character(as.numeric(Male_income)),
         Female_Income_n = as.character(as.numeric(Female_income))
         )
Income_by_gender <- Income_ %>%
  mutate(
    Male_Income_n = as.numeric(as.character(Male_Income_n)),
    Female_Income_n = as.numeric(as.character(Female_Income_n)),
    Gender_pay_gap = round((Male_Income_n - Female_Income_n) / Male_Income_n * 100,1)
  )|>
  select(Area.name,Annual_Pay_n,Male_Income_n,Female_Income_n,Gender_pay_gap)|>
  arrange(desc(Gender_pay_gap))|>
  head(10)

 Income_by_gender
```


# Task 5



### The Quick Sketch (Base R Histogram)

```{r}
library(ggplot2)
```


```{r}
# Choose one numeric variable
hist(highest_population_age$Average.Age..2016,
     main = "Frequency of average age",
     xlab = "Average age",
     col = "lightblue",
     border =  "purple")

```

### The Relationship Map (ggplot2 Scatter Plot)

```{r}
library(ggplot2)

ggplot(Income_by_gender, aes(x= `Male_Income_n`, y= `Female_Income_n`)) +
  geom_point(alpha = 0.5,  color = "darkblue", size = 2.5) +
  geom_smooth(color = "pink") +
  labs(title = "Annual income divided by gender",
       subtitle = "Coloured by Terézia M. Balážová",
       x = "Male annual income",
       y = "Female annual income",
       color = "Legend") +
  theme_minimal()
ggsave("Annual income by gender.png", width = 8, height = 6)
```

# The Comparison (ggplot2 Boxplot)
```{r}
ggplot(data = inner_London, aes(x= log_inner_london, y= Employment.rate......2015., fill = log_inner_london))+
  geom_boxplot() +
  geom_col() +
  labs(title = "Employment rate in Inner and Outer London ",
       x = "Inner London",
       y = "Employment rate") +
  theme_dark() +
  theme(legend.position = "right") 

ggsave("Employment_London.png", width = 6, height = 6)
```

# The “Deep Dive” (Faceting or Custom)
```{r}
ggplot(data = Income_by_gender, aes(x = Gender_pay_gap))+
  geom_histogram(binwidth = 2,fill = "moccasin", color = "dodgerblue3") +
  facet_wrap(~ Area.name)+
  labs(
    title = "Gender pay gap in areas across London",
    x = "Pay gap",
    y = "Area"
  )

```
# export
```{r}
ggsave("London_plot.png", width = 6, height = 6)
```

